MODEL:
  WEIGHT: ""
  ARCHITECTURE: "TCN"
  TCN:
    NUM_CLIPS: 16
    FEATPOOL:
      INPUT_SIZE: 500
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 16
    FEAT2D:
      POOLING_COUNTS: [15]
    INTEGRATOR:
      QUERY_HIDDEN_SIZE: 512
      LSTM:
        NUM_LAYERS: 3
        BIDIRECTIONAL: False
    PREDICTOR:
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 5
      NUM_STACK_LAYERS: 4
    LOSS:
      MIN_IOU: 0.5
      MAX_IOU: 1.0
DATASETS:
  TRAIN: ("activitynet_train", )
  VAL: ("activitynet_val", )
  TEST: ("activitynet_test",)
  TEST_1: ("activitynet_ood_test_30",)
  TEST_2: ("activitynet_ood_test_60",)  
INPUT:
  NUM_PRE_CLIPS: 256
  PRE_QUERY_SIZE: 300
DATALOADER:
  NUM_WORKERS: 0
SOLVER:
  LR: 0.0001
  BATCH_SIZE: 32
  MILESTONES: (20, 30)
  MAX_EPOCH: 20
TEST:
  NMS_THRESH: 0.5
  BATCH_SIZE: 32
